CB.CloudApp.init('yegguroxoyua', '47345f24-5127-4318-abd3-b054fe11a2a2');

class ingredient {
	constructor(name,image){
		this.name = name;
		this.image = image;
	}
}

const Steak = new ingredient("Steak","https://2.bp.blogspot.com/-OzQU3JPQbiE/V4PEP3yF0pI/AAAAAAAAxnk/WmXXTcMVKgILHcdUd8bw9PVw0FNiJCUGwCLcB/s1600/hp1-steak.png");
const Salt = new ingredient("Salt","http://www.yupik.ca/images/images_l/20156p.jpg");
const Pepper = new ingredient("Pepper","https://cdn.shopify.com/s/files/1/0219/5528/products/garlic-pepper_large.png?v=1379807620");
const Broccoli = new ingredient("Broccoli","http://www.pngmart.com/image/8367");
const Rice_Pilaf = new ingredient("Rice Pilaf","http://www.neareast.com/images/default-source/product-images/rice-pilaf/product-images/original.png?sfvrsn=4");
const Chicken = new ingredient("Chicken","http://www.basicfoodflavors.com/wp-content/uploads/2016/05/roast-chicken.png");
const Honey = new ingredient("Honey","http://www.melitahoney.com/wp-content/uploads/2014/05/our-honey-drip.png");
const Mustard = new ingredient("Mustard","https://aqu52.files.wordpress.com/2016/05/dijon-mustard.png?w=300");
const Olive_Oil = new ingredient("Olive Oil","http://www.mangataworld.com/wp-content/uploads/2015/09/Olive-oil-bottle-trans.png");
const Farro = new ingredient("Farro","https://www.cerealbio.it/uploads/farro.png");
const Cheddar_Cheese = new ingredient("Cheddar Cheese","https://www.goodgracestreats.com/wp-content/uploads/2015/01/cheddar-cheese.png");
const Milk = new ingredient("Milk","https://cdn.pixabay.com/photo/2014/09/04/05/27/milk-435295_960_720.png");
const Eggs = new ingredient("Eggs","http://pngimg.com/upload/egg_PNG25.png");
const Onion_Powder = new ingredient("Onion Powder","http://thespicepeople.com.au/wp-content/uploads/2014/02/onion-powder.png");
const Bisquick = new ingredient("Bisquick","http://www.lifemadedelicious.ca/en/-/media/Images/LMD/Brands/Sub-Product/bettycrockerbaking/Changes/Bisquick/Bisquick.png");
const Ground_Beef = new ingredient("Ground Beef","http://www.bergenmeats.com/images/BfImages/Ground-Beef.gif");
const Bell_Peppers = new ingredient("Bell Peppers","https://costafarm.com/wp-content/uploads/2015/01/product_bellpeppers2.png");
const Jalapeno_Peppers = new ingredient("Jalape&#241;o Pepppers","https://static1.squarespace.com/static/542c2adce4b00b7cfca0891c/5461070ce4b0f587f5cef935/56a2fd7c89a60a06d6c808d6/1453522302863/poblano.png?format=500w");
const Kidney_Beans = new ingredient("Kidney Beans","http://michiganbean.org/wp-content/uploads/2013/09/MichiganBean_RedKidney.png");
const Onion = new ingredient("Onion","https://www.onion-router.net/Images/onion.gif");
const Chili_Powder = new ingredient("Chili Powder","http://www.hillscalling.co/wp-content/uploads/2016/04/Chili-Powder-180x180.png");
const Cumin = new ingredient("Cumin","https://cdn.shopify.com/s/files/1/0219/5528/products/cumin-ground_1024x1024.png?v=1368712346");
const Coriander = new ingredient("Coriander","http://cdn.shopify.com/s/files/1/1178/4972/products/ground_coriander-my_moms_cookbook-cookbook-spices-seasonings_grande.png?v=1460326064");
const Crushed_Tomatoes = new ingredient("Crushed Tomatoes in Puree","http://redpacksauce.com/images/products/Ready-Cut-Chopped-Tomatoes-in-Puree.gif");
const Lemon = new ingredient("Lemon","http://www.drdeborahbaker.com/wp-content/uploads/2014/07/lemon.png");
const Flour = new ingredient("Flour","http://s3.amazonaws.com/images.onedegreeorganics.com/assets/8124/Oat_Flour_web_ing_cat_l.png?1408680922");
const White_Wine = new ingredient("White Wine","http://downloadicons.net/sites/default/files/white-wine-icon-54597.png");
const Capers = new ingredient("Capers","http://www.reesespecialtyfoods.com/sites/default/files/products/single/Non-Pareil-Capers-3.5oz.png");
const Butter = new ingredient("Butter","http://www.pngall.com/wp-content/uploads/2016/07/Butter-Transparent.png");
const Risotto = new ingredient("Risotto","https://justaddcooking.com/recipes/overhead/asparagus_risotto.png");
const Wax_Beans = new ingredient("Wax Beans","https://www.sakurafresh.com/bangalore/image/cache/catalog/sf_products/others/First%20Agro%20Yellow%20Wax%20Beans-800x800.png");
const Tortillas = new ingredient("Tortillas","http://www.santamariafoodservice.com/globalassets/flavour/tex-mex/4780-tortilla.png?w=384&h=448");
const Yogurt = new ingredient("Yogurt","http://www.pavels.net/wp-content/themes/pavels-bootscores/images/yogurt_cup_500x500.png");
const Taco_Sauce = new ingredient("Taco Sauce","https://images6.jetcdn.net/md5/ea984383277e48756f2cc340d170a3e3.500");
const Tomatoes = new ingredient("Tomatoes","http://static.pulse.ng/img/incoming/origs4009888/4640488343-w980-h640/tamato.png");
const Lettuce = new ingredient("Lettuce","http://onlystaples.com/pub/media/catalog/product/cache/1/image/265x265/beff4985b56e3afdbeabfc89641a4582/l/e/lettuce_1_2.png");
const Ketchup = new ingredient("Ketchup","http://www.koshary.be/wp-content/uploads/2016/05/ketchup-600x322.png");
const Bread_Crumbs = new ingredient("Bread Crumbs","http://www.paganichef.it/ufiles/medium/53ce693f762491.227612081.png?1470053301");
const Mustard_Powder = new ingredient("Mustard Powder","http://www.vermontsmokeandcure.com/wp-content/uploads/2015/09/mustard-powder-mustardseed-300x300.png");
const Sage = new ingredient("Sage","https://www.bulkherbstore.com/pub/media/catalog/product/cache/1/image/700x560/e9c3970ab036de70892d86c6d221abfe/s/a/sage-leaf-rubbed.png");
const Worcestershire_Sauce = new ingredient("Worcestershire Sauce","http://83b42ac7127a66efcd44-7472e97167182b9fdadfa91da0cf9729.r93.cf5.rackcdn.com/catalog/product/cache/1/image/1252x1252/9df78eab33525d08d6e5fb8d27136e95/4/1/4150001310cf.gif");
const Green_Beans = new ingredient("Green Beans","http://foodservice.bonduelleamericas.com/media/cache/94/c1/94c127d98e32c7669fcadff20524ad07.png");
const Feta_Cheese = new ingredient("Feta Cheese","http://thecarolinamarket.com/media/extendware/ewimageopt/media/inline/41/d/feta-6b0.png");
const Spinach = new ingredient("Spinach","http://www.naturalineco.com/kindeditor/attached/image/20140926/20140926231629_9834.png");
const Shells = new ingredient("Shells","http://www.fooduniversity.com/foodu/PantryIngredients/Pasta/Shapes/largeShell.gif");
const Ricotta_Cheese = new ingredient("Ricotta Cheese","https://www.dairygoodness.ca/var/ezflow_site/storage/images/dairy-goodness/home/cheese/all-you-need-is-cheese/cheese-life/simple-solutions/canadian-ricotta-our-top-four-breakfasts/9855415-5-eng-CA/canadian-ricotta-our-top-four-breakfasts.png");
const Mozzarella_Cheese = new ingredient("Mozzarella Cheese","http://french-products.fr/contents/media/l_mozzarella_.png");
const Parmesean_Cheese = new ingredient("Parmesean Cheese","https://dtgxwmigmg3gc.cloudfront.net/files/534b590ac566d76f040005b0-icon-256x256.png");
const Nutmeg = new ingredient("Nutmeg","https://cdn.shopify.com/s/files/1/0219/5528/products/nutmeg-ground_1024x1024.png?v=1368717538");
const Tomato_Sauce = new ingredient("Tomato Sauce","http://www.parshift.com/ovens/Secrets/images/PasSauc2.gif");
const Potatoes = new ingredient("Potatoes","http://downloadclipart.org/do-upload/clipart/2016-05/Potato.png");
const Mushrooms = new ingredient("Mushrooms","http://www.gmushrooms.com/pots/Blue-Oyster.gif");
const Balsamic_Vinegar = new ingredient("Balsamic Vinegar","http://www.villabertolli.com/wp-content/uploads/sites/3/2014/12/524-11471011.png");
const Rosemary = new ingredient("Rosemary","http://goodmorningcenter.com/wp-content/uploads/2014/10/Rosemary.png");
const Corn = new ingredient("Corn","http://pngimg.com/upload/corn_PNG5268.png");
const Parsley = new ingredient("Parsley","http://bengardranch.com/wp-content/uploads/2012/03/parsley_i1.png");
const Spaghetti = new ingredient("Spaghetti","http://www.thechampionpizza.com/wp-content/uploads/2013/10/Spaghetti-MeatSauce-300x300.png");
const Tuna = new ingredient("Tuna","http://www.makarosa.com.cn/img/meat-MA01.png");
const Macaroni = new ingredient("Macaroni","http://www.bellaitaliaproducts.com/media/0/63295874078038/2.png");
const Cream_of_Celery = new ingredient("Cream of Celery Soup","https://cdn-media.shophero.com/p/nv6mqyjdgo/Campbells_Healthy_Request_Cream_of_Celery_Soup_1075oz.png");
const Peas = new ingredient("Peas","http://fastcovai.com/wp-content/uploads/2014/09/pattani-pea.png");
